frehanza/urls.py
from django.urls import path,include
from . import views
from .views import (
  index,
  create,
  detail,
  delete,
)

app_name = 'frehanza'

urlpatterns = [
    path('', views.home, name='home'),
    path('about/', views.about, name='about'),
    path('scheduler/', create, name='forms'),
    path('scheduler/list/', index, name='index'),
    path('scheduler/details/<int:my_id>', detail, name='detail'),
    path('scheduler/delete/<int:my_id>', delete, name='delete')
]

story/urls.py
from django.contrib import admin
from django.urls import path, include


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('frehanza.urls')),
]

frehanza/models.py
from django.db import models

# Create your models here.
class Scheduler(models.Model):
  course = models.CharField(max_length=128)
  lecturer = models.CharField(max_length=128)
  credits = models.IntegerField(default=0)
  description = models.TextField(max_length=128)
  term = models.CharField(max_length=128)
  room = models.CharField(max_length=128)



  def __str__(self):
    return f'{self.course} ({self.credits} sks) : {self.lecturer} '

frehanza/forms.py
from django.forms import ModelForm
from .models import Scheduler

class SchedulerForm(ModelForm):
    class Meta:
        model = Scheduler
        fields = '__all__'

frehanza/views.py
from django.shortcuts import render, redirect
from django.urls import reverse

# Models
from .models import Scheduler

# Form
from .forms import SchedulerForm

# Create your views here.
def home(request):
    return render(request, 'home.html')

def about(request):
    return render(request, 'about.html') 

def index(request):
    course_list = Scheduler.objects.all()
    context={
    "course_list": course_list
    }
    return render(request, "index.html", context)
 

def create(request):
  print("Masuk Create")
  success_notif = ''
  error_notif = ''
  if (request.method == 'POST') :
    print("Masuk Post")
    form = SchedulerForm(request.POST)
    if form.is_valid():
      print("Masuk valid")
      new_scheduler = Scheduler(
        course = request.POST['course'],
        lecturer = request.POST['lecturer'],
        credits = request.POST['credits'],
        description = request.POST['description'],
        term = request.POST['term'],
        room = request.POST['room']
      )
      new_scheduler.save()
      success_notif = 'Successfully Added!'
      return redirect('/scheduler/list/')
    else:
      error_notif = 'Failed!'
  else:
    form = SchedulerForm()

  context = {
    'form': form,
  }
  return render(request,'forms.html', context)

def detail(request, my_id):
  scheduler = Scheduler.objects.get(id = my_id)
  context = {
    "scheduler": scheduler,
  }
  return render(request, "details.html", context)

def delete(request, my_id):
  scheduler = Scheduler.objects.get(id = my_id)
  scheduler.delete()
  return redirect('/scheduler/list/')

frehanza/templates/about.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0s">

   
    <link rel="apple-touch-icon" sizes="180x180" href="{% static 'apple-touch-icon.png' %}">
    <link rel="icon" type="image/png" sizes="32x32" href="{% static 'favicon-32x32.png' %}">
    <link rel="icon" type="image/png" sizes="16x16" href="{% static 'favicon-16x16.png' %}">
    <link rel="mask-icon" href="{% static 'safari-pinned-tab.svg' %}" color="#5bbad5">
    <meta name="msapplication-TileColor" content="#da532c">
    <meta name="theme-color" content="#ffffff">

    <title>Frehanza</title>

    <link rel="stylesheet" href="{% static 'about.css' %}">
    <link href="https://fonts.googleapis.com/css2?family=Montserrat:wght@700&display=swap" rel="stylesheet">
    <link rel="stylesheet"  href="https://use.fontawesome.com/releases/v5.0.7/css/all.css" />

    
</head>

<body>
  <nav class="nav">
    <div class="container">
        <div class="logo">
            <a href="{% url 'frehanza:home' %}"><img src="{% static 'favicon-32x32.png' %}" alt="F"></a>
        </div>
        <div id="mainListDiv" class="main_list">
            <ul class="navlinks">
                <li><a href="{% url 'frehanza:about' %}">About</a></li>
                <li><a href="#">Portfolio</a></li>
                <li><a href="#">Contact</a></li>
                <li><a href="{% url 'frehanza:forms' %}">Scheduler</a></li>
                <li><a href="http://story1-frehanza.herokuapp.com/Story1.html">Blog</a></li>
            </ul>
        </div>
        <span class="navTrigger">
            <i></i>
            <i></i>
            <i></i>
        </span>
    </div>
</nav>


     <!-- this is the markup. you can change the details (your own name, your own avatar etc.) but don’t change the basic structure! -->

<aside class="profile-card">
  
    <header>
      
      <!-- here’s the avatar -->
      <a href="{% url 'frehanza:home' %}">
        <img src="{% static 'reha.png' %}">
      </a>
  
      <!-- the username -->
      <h1>Fareeha Nisa Zayda Azeeza</h1>
      
      <!-- and role or location -->
      <h2>Student</h2>
      
    </header>
    
    <!-- bit of a bio; who are you? -->
    <div class="profile-bio">
      
      <p>Interest: Food, Design, Art, Music, Dance & Travel</p>
      
    </div>
    
    <!-- some social links to show off -->
    <ul class="profile-social-links">
      
     <!-- linkedin profile-->
     <li>
        <a href="//id.linkedin.com/in/fareeha-nisa-zayda-azeeza-79b42411a">
          <img src="{% static 'LinkedIn.svg' %}">
        </a>
      </li>

      <!-- twitter - el clásico  -->
      <li>
        <a href="twitter.com/vaniloquenche">
          <img src="{% static 'Twitter.svg' %}">
        </a>
      </li>
      
      <!-- envato – use this one to link to your marketplace profile -->
      <li>
        <a href="www.instagram.com/frehanza/?hl=id">
          <img src="{% static 'Instagram.svg' %}">
        </a>
      </li>
      
      <!-- codepen - your codepen profile-->
      <li>
        <a href="open.spotify.com/user/frehanza?si=TaUaiipISP2XE8uofwWH-g">
          <img src="{% static 'spotify.svg' %}">
        </a>
      </li>
      
      <!-- add or remove social profiles as you see fit -->
      
    </ul>
    
  </aside>
  <!-- that’s all folks! -->
  

    <footer>
        <span class="logo">A unique<br>Copyright</span>
       <div class="box">
        <span class="box__copy">©</span>
         <div class="box__group">
           <p class="box__date">2020 Frehanza</p>
         <hr>
         <a class="box__link" href="https://mail.google.com/mail/?view=cm&fs=1&tf=1&to=frehanza@gmail.com">Contact Me</a>
         </div>
       </div> 
      </footer>


    <!-- Jquery needed -->
<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.1.1/jquery.min.js"></script>
<script src="js/scripts.js"></script>

<!-- Function used to shrink nav bar removing paddings and adding black background -->
<script>
    $(window).scroll(function() {
        if ($(document).scrollTop() > 50) {
            $('.nav').addClass('affix');
            console.log("OK");
        } else {
            $('.nav').removeClass('affix');
        }
    });
</script>

<script>
    $('.navTrigger').click(function () {
    $(this).toggleClass('active');
    console.log("Clicked menu");
    $("#mainListDiv").toggleClass("show_list");
    $("#mainListDiv").fadeIn();
});
</script>


</body>
</html>

frehanza/templates/base.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0s">

    <link rel="apple-touch-icon" sizes="180x180" href="{% static 'apple-touch-icon.png' %}">
    <link rel="icon" type="image/png" sizes="32x32" href="{% static 'favicon-32x32.png' %}">
    <link rel="icon" type="image/png" sizes="16x16" href="{% static 'favicon-16x16.png' %}">
    <link rel="mask-icon" href="{% static 'safari-pinned-tab.svg' %}" color="#5bbad5">
    <meta name="msapplication-TileColor" content="#da532c">
    <meta name="theme-color" content="#ffffff">

    <title>Frehanza</title>

    <link rel="stylesheet" href="{% static 'main.css' %}">
    <link rel="stylesheet" href="{% static 'story5.css' %}">

    <link href="https://fonts.googleapis.com/css2?family=Montserrat:wght@700&display=swap" rel="stylesheet">

</head>

<body>

    <nav class="nav">
        <div class="container">
            <div class="logo">
                <a href="{% url 'frehanza:home' %}"><img src="{% static 'favicon-32x32.png' %}" alt="F"></a>
            </div>
            <div id="mainListDiv" class="main_list">
                <ul class="navlinks">
                    <li><a href="{% url 'frehanza:about' %}">About</a></li>
                    <li><a href="#">Portfolio</a></li>
                    <li><a href="#">Contact</a></li>
                    <li><a href="{% url 'frehanza:forms' %}">Scheduler</a></li>
                    <li><a href="http://story1-frehanza.herokuapp.com/Story1.html">Blog</a></li>
                </ul>
            </div>
            <span class="navTrigger">
                <i></i>
                <i></i>
                <i></i>
            </span>
        </div>
    </nav>

    {% block body %}
    {% endblock %}

    <footer>
        <span class="logo">A unique<br>Copyright</span>
       <div class="box">
        <span class="box__copy">©</span>
         <div class="box__group">
           <p class="box__date">2020 Frehanza</p>
         <hr>
         <a class="box__link" href="https://mail.google.com/mail/?view=cm&fs=1&tf=1&to=frehanza@gmail.com">Contact Me</a>
         </div>
       </div> 
      </footer>

    <script src="https://cdn.jsdelivr.net/npm/typed.js@2.0.11"></script>
    
    <script>
          var typed = new Typed(".animate", {
            strings: [
                "Student","Fighter","Dreamer"
            ],
            typeSpeed: 50,
            backSpeed: 50,
            loop: true
        });
    </script>

<!-- Jquery needed -->
<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.1.1/jquery.min.js"></script>


<!-- Function used to shrink nav bar removing paddings and adding black background -->
<script>
    $(window).scroll(function() {
        if ($(document).scrollTop() > 50) {
            $('.nav').addClass('affix');
            console.log("OK");
        } else {
            $('.nav').removeClass('affix');
        }
    });
</script>

<script>
    $('.navTrigger').click(function () {
    $(this).toggleClass('active');
    console.log("Clicked menu");
    $("#mainListDiv").toggleClass("show_list");
    $("#mainListDiv").fadeIn();
});
</script>


</body>
</html>

frehanza/templates/details.html
{% extends 'base.html' %}
{% load static %}

{% block body %}


<section>
    
    {% if scheduler %}
    <div class="table-container">
        <h1>Detail {{ scheduler.course }}</h1>
    <table>
        <tr>
            <th id="title"><b>Course Name</b></th>
            <th id="title"><b>Lecturer</b></th>
            <th id="title"><b>Credits</b></th>
            <th id="title"><b>Term</b></th>
            <th id="title"><b>Description</b></th>
            <th id="title"><b>Room</b></th>
        </tr>
        <tr>
            <th>{{ scheduler.course }}</th>
            <th>{{ scheduler.lecturer }}</th>
            <th>{{ scheduler.credits }}</th>
            <th>{{ scheduler.term }}</th>
            <th>{{ scheduler.description }}</th>
            <th>{{ scheduler.room }}</th>
        </tr>
    </table>

    <a href="{% url 'frehanza:home' %}"><button class="button3" type="submit">Back</button></a>

    </div>

    

    {% endif %}
</section>

{% endblock %}

frehanza/templates/forms.html
<!DOCTYPE html>

{% extends 'base.html' %}
{% load static %}
{% block body %}

<html lang="en">
<head>
    <link rel="stylesheet" href="{% static 'forms.css' %}">
</head>

<style>

    .page {
  
    display: flex;
    flex-direction: column;
    height: calc(100% - 210px);
    place-content: center;
    width: calc(100% - 40px);
    margin-bottom: 1000px;
    }

    @media (max-width: 767px) {
    .page {
      height: auto;
      padding-top: 50px;
      margin-bottom: 20px;
      padding-bottom: 20px;
      background-size: cover;
    }
  }
   
    .right {
    background: #141414;
    box-shadow: 0px 0px 40px 16px rgba(0,0,0,0.22);
    color: #F1F1F2;
    width: 750px;
    height: 700px;
  }

   @media (max-width: 767px) {
    .right {
      flex-shrink: 0;
      height: 100%;
      width: 100%;
      max-height: 600px;
    }
  }

  .eula {
    font-family: 'Barlow Medium';
    color: #999;
    font-size: 14px;
    line-height: 1.5;
    margin: 40px;
    margin-top: 10px;
  }
  
  /* Button */
  button {
    height: 40px;
    margin-left: -4px;
    margin-top: 20px;
    text-align: center;
    width: 130px;
    border-radius: 40px;
    border: 2px solid #141414;
    background: linear-gradient(149deg, rgba(166,224,236,1) 9%, rgba(210,187,229,1) 31%, rgba(233,169,227,1) 52%, rgba(255,165,205,1) 77%, rgba(252,185,215,1) 94%);
    letter-spacing: 1px;
    font-size: 12px;
    font-weight: bold;
    cursor: pointer;
    transition: all 0.25s ease;
}

.button2 {
    height: 40px;
    margin-left: 10px;
    margin-top: 20px;
    text-align: center;
    width: 130px;
    border-radius: 40px;
    border: 2px solid #141414;
    background: linear-gradient(149deg, rgba(166,224,236,1) 9%, rgba(210,187,229,1) 31%, rgba(233,169,227,1) 52%, rgba(255,165,205,1) 77%, rgba(252,185,215,1) 94%);
    letter-spacing: 1px;
    font-size: 12px;
    font-weight: bold;
    cursor: pointer;
    transition: all 0.25s ease;
}
</style> 
<body>


<section class="page">
  <div class="form-container">
    <div class="left">
      <div class="login"> Sche-<br>duler </div>
      <div class="eula">Add your schedule here</div>
    </div>
    <div class="right">
      <svg viewBox="0 0 320 300">
        <defs>
          <!-- <linearGradient
                          inkscape:collect="always"
                          id="linearGradient"
                          x1="13"
                          y1="193.49992"
                          x2="307"
                          y2="193.49992"
                          gradientUnits="userSpaceOnUse">
            <stop
                  style="stop-color:  rgba(115,198,240,1);"
                  offset="0"
                  id="stop876" />
            <stop
                  style="stop-color:rgba(172,131,235,1);"
                  offset="0"
                  id="stop876" />      
            <stop
                  style="stop-color:rgba(244,132,218,1);"
                  offset="0"
                  id="stop878" />
            <stop
                  style="stop-color:rgba(115,198,240,1);"
                  offset="2"
                  id="stop879" />
            <stop
                  style="stop-color:rgba(244,132,218,1);"
                  offset="3"
                  id="stop880" />
            <stop
                  style="stop-color:rgba(255,215,117,1);"
                  offset="4"
                  id="stop881" />
            <stop
                  style="stop-color:rgba(255,234,97,1);"
                  offset="5"
                  id="stop882" />
          </linearGradient> -->
        </defs>
        <path d="m 40,120.00016 239.99984,-3.2e-4 c 0,0 24.99263,0.79932 25.00016,35.00016 0.008,34.20084 -25.00016,35 -25.00016,35 h -239.99984 c 0,-0.0205 -25,4.01348 -25,38.5 0,34.48652 25,38.5 25,38.5 h 215 c 0,0 20,-0.99604 20,-25 0,-24.00396 -20,-25 -20,-25 h -190 c 0,0 -20,1.71033 -20,25 0,24.00396 20,25 20,25 h 168.57143" />
      </svg>
      <form class="form" action="" method="POST">
        {% csrf_token %}
        {{form}}

        <button class="button"></button>
        <a href="{% url 'frehanza:index' %}"><button class="button2">List </button></a>

      </div>
    </div>
  </div>
</section>

{% endblock %}

<script>
    $(function() {
  $( "#button" ).click(function() {
    $( "#button" ).addClass( "onclic", 250, validate);
  });

  function validate() {
    setTimeout(function() {
      $( "#button" ).removeClass( "onclic" );
      $( "#button" ).addClass( "validate", 450, callback );
    }, 2250 );
  }
    function callback() {
      setTimeout(function() {
        $( "#button" ).removeClass( "validate" );
      }, 1250 );
    }
  });
</script>



</body>


</html>

frehanza/templates/home.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0s">

    <link rel="apple-touch-icon" sizes="180x180" href="{% static 'apple-touch-icon.png' %}">
    <link rel="icon" type="image/png" sizes="32x32" href="{% static 'favicon-32x32.png' %}">
    <link rel="icon" type="image/png" sizes="16x16" href="{% static 'favicon-16x16.png' %}">
    <link rel="mask-icon" href="{% static 'safari-pinned-tab.svg' %}" color="#5bbad5">
    <meta name="msapplication-TileColor" content="#da532c">
    <meta name="theme-color" content="#ffffff">

    <title>Frehanza</title>

    <link rel="stylesheet" href="{% static 'main.css' %}">
    <link href="https://fonts.googleapis.com/css2?family=Montserrat:wght@700&display=swap" rel="stylesheet">

</head>

<body>

    <nav class="nav">
        <div class="container">
            <div class="logo">
                <a href="{% url 'frehanza:home' %}"><img src="{% static 'favicon-32x32.png' %}" alt="F"></a>
            </div>
            <div id="mainListDiv" class="main_list">
                <ul class="navlinks">
                    <li><a href="{% url 'frehanza:about' %}">About</a></li>
                    <li><a href="#">Portfolio</a></li>
                    <li><a href="#">Contact</a></li>
                    <li><a href="{% url 'frehanza:forms' %}">Scheduler</a></li>
                    <li><a href="http://story1-frehanza.herokuapp.com/Story1.html">Blog</a></li>
                </ul>
            </div>
            <span class="navTrigger">
                <i></i>
                <i></i>
                <i></i>
            </span>
        </div>
    </nav>

    <section class="landing">
        
        <div class="wrapper">
            <header>
               <div class="header-image">
                <h1>Hi, I'm Reha. <br>
                    I'm a <span class="animate"></span></h1>

                <a href="{% url 'frehanza:about' %}"><img src="{% static 'Learn More.svg' %}" alt="Learn More"></a>
                </div>

             
             
            </header>

            
        </div>
    </section>
   

    <section class="about">
        <div class="about-container">
            <div class="row">
                <div class="col-md-5">
 
                    <img src="{% static 'me.jpg' %}" alt="Reha" style="width: 309px; height: 317px; left: 100px; margin-top: 60px;">
                </div>
            </div>
            <br>
            <div class="col-md-7-about-right">

                <h1> About </h1>

                <p>
                    My name is Fareeha Nisa Zayda Azeeza, you can call me Reha. 
                    I am currently a sophomore majoring in Information System (Batch 2019) at University of Indonesia. 
                    <br>My hobbies are strolling through the city, doing a culinary journey, designing, dancing, and reading. 
                    My dream is to become someone who is success and beneficial to others.
                    <br>
                    <br>
                    I  (want) to be able to specialize in <span> Design (Product Design, Visual Design, Web Design, Branding), User Interface/User Experience (UI/UX) and Editing (Photos & Videos).</span>
                </p> 
                
                <div class="card">

                    <div class="slider">
                        <div class="item">
                            <div class="item-inner">
                                <img src="{% static '30+.svg' %}" alt="">
                                <h4> Total Works </h4>
                            </div>
                        </div>
                        <div class="item">
                            <div class="item-inner">
                                <img src="{% static '10+.svg' %}" alt="">
                                <h4> Experiences </h4>
                            </div>
                        </div>
                        <div class="item">
                            <div class="item-inner">
                                <img src="{% static '10+.svg' %}" alt="">
                                <h4> Works Featured </h4>
                            </div>
                        </div>
                        <div class="item">
                            <div class="item-inner">
                                <img src="{% static '10+.svg' %}" alt="">
                                <h4> Skills </h4>
                            </div>
                        </div>
                    </div>
                    
                </div>
          
                <a href="#"><img src="{% static 'download-resume.svg' %}" alt="Download Resume"></a>

            </div>
        </div>
    </section>

    <footer>
        <span class="logo">A unique<br>Copyright</span>
       <div class="box">
        <span class="box__copy">©</span>
         <div class="box__group">
           <p class="box__date">2020 Frehanza</p>
         <hr>
         <a class="box__link" href="https://mail.google.com/mail/?view=cm&fs=1&tf=1&to=frehanza@gmail.com">Contact Me</a>
         </div>
       </div> 
      </footer>

    <script src="https://cdn.jsdelivr.net/npm/typed.js@2.0.11"></script>
    <script src="typed.js"></script>
    <script>
          var typed = new Typed(".animate", {
            strings: [
                "Student","Fighter","Dreamer"
            ],
            typeSpeed: 50,
            backSpeed: 50,
            loop: true
        });
    </script>

<!-- Jquery needed -->
<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.1.1/jquery.min.js"></script>
<script src="js/scripts.js"></script>

<!-- Function used to shrink nav bar removing paddings and adding black background -->
<script>
    $(window).scroll(function() {
        if ($(document).scrollTop() > 50) {
            $('.nav').addClass('affix');
            console.log("OK");
        } else {
            $('.nav').removeClass('affix');
        }
    });
</script>

<script>
    $('.navTrigger').click(function () {
    $(this).toggleClass('active');
    console.log("Clicked menu");
    $("#mainListDiv").toggleClass("show_list");
    $("#mainListDiv").fadeIn();
});
</script>


</body>
</html>

frehanza/templates/index.html
{% extends 'base.html' %}
{% load static %}


{% block body %}

<section>

    {% if course_list %}
    <div class="table-container">

    <h1 class="course">Course List</h1>

    <table>
        <tr>
            <th id="title"><b>Course Name</b></th>
            <th id="title"><b>Description</b></th>
            <th></th>
            <th>
        </tr>
        {% for courses in course_list %}
        <tr>
            <th>{{ courses.course }}</th>
            <th>{{ courses.description }}</th>
            <th><a href="{% url 'frehanza:detail' my_id=courses.id %}"><button class="button3" type="submit">Detail</button></a></th>
            <th><a href="{% url 'frehanza:delete' my_id=courses.id %}"><button class="button3" type="submit">Delete</button></a></th>
        </tr>
        {% endfor %}
    </table>
    </div>
    {% endif %}
        
</section>


{% endblock %}